# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DfirCli < Formula
  desc "DFIR Lab CLI — digital forensics and incident response toolkit"
  homepage "https://dfir-lab.ch"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dfir-lab/dfir-cli-releases/releases/download/v0.1.0/dfir-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "6815f2b72c0d44731fb45a94423a631b7eb3a5c5570599b4192016064defb5dd"

      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dfir-lab/dfir-cli-releases/releases/download/v0.1.0/dfir-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "5f0053eee66cc36cda4b837803883878274a723868fdcfb61b00467c7a148e6b"

      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dfir-lab/dfir-cli-releases/releases/download/v0.1.0/dfir-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "9e6d1531a00f1278fb7b1a9cb91e94cd9fe8e75b0bbfaf57898784acf9636667"
      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dfir-lab/dfir-cli-releases/releases/download/v0.1.0/dfir-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "1353d44f097a7e5956e9e6df11107f64a0f515afca6daf0c5d4870711d01abd6"
      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
      end
    end
  end

  test do
    system "#{bin}/dfir-cli", "--version"
  end
end
