# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DfirCli < Formula
  desc "DFIR Lab CLI — digital forensics and incident response toolkit"
  homepage "https://dfir-lab.ch"
  version "0.1.7"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dfir-lab/dfir-cli-releases/releases/download/v0.1.7/dfir-cli_0.1.7_darwin_amd64.tar.gz"
      sha256 "6bdb63a71ffae0a85d1e8bbc8274309a38d2701fd5c911f0d575b45bf0afdd12"

      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dfir-lab/dfir-cli-releases/releases/download/v0.1.7/dfir-cli_0.1.7_darwin_arm64.tar.gz"
      sha256 "b8bde095987faec75f8773702d8f85e162197359e37cffb93ad83eb2a8317fc9"

      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dfir-lab/dfir-cli-releases/releases/download/v0.1.7/dfir-cli_0.1.7_linux_amd64.tar.gz"
      sha256 "55125b2c9ad4fd0d0934ea44805936063c2d538bc7bb2a8f05b706d37d3fdefa"
      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dfir-lab/dfir-cli-releases/releases/download/v0.1.7/dfir-cli_0.1.7_linux_arm64.tar.gz"
      sha256 "ec49b4b6ca3f27f863601e040b04dea215ddd1f3cfab57cf5a02c4c90ad77378"
      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
        man1.install Dir["man/*.1"]
      end
    end
  end

  def caveats
    <<~EOS
      To get started, make sure Homebrew's bin directory is in your PATH:

        export PATH="$(brew --prefix)/bin:$PATH"

      Then reload your shell session:

        exec $SHELL -l

      Configure your API key:

        dfir-cli config init

      Get your API key from https://dfir-lab.ch
    EOS
  end

  test do
    system "#{bin}/dfir-cli", "--version"
  end
end
